# Generated by Django 4.2.16 on 2026-03-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_usercontactprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
